#!/usr/bin/env python3
"""Generate the Consolidation-3 fov3d compatibility facade.

This script deliberately does not alter legacy implementation modules.  It creates
small modules that re-export them under conceptual names so future development can
stop depending on historical tools/* module names.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def module_path(root: Path, dotted: str) -> Path:
    return root.joinpath(*dotted.split(".")).with_suffix(".py")


def ensure_packages(root: Path, dotted: str) -> None:
    parts = dotted.split(".")[:-1]
    cur = root
    for part in parts:
        cur = cur / part
        cur.mkdir(exist_ok=True)
        init = cur / "__init__.py"
        if not init.exists():
            init.write_text('"""Foveal Stereo Vision conceptual package."""\n', encoding="utf-8")


def wrapper_text(legacy: str, cli: bool) -> str:
    body = f'''"""Compatibility facade for :mod:`{legacy}`.

Generated by Consolidation 3.  Scientific implementation remains sealed in the
minimal legacy engine; new code imports this conceptual namespace instead.
"""
from fov3d._compat import reexport_legacy

reexport_legacy(globals(), {legacy!r})
'''
    if cli:
        body += '''\nif __name__ == "__main__":\n    _main = globals().get("main")\n    if _main is None:\n        raise SystemExit("legacy module does not expose main()")\n    raise SystemExit(_main())\n'''
    return body


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[2])
    ap.add_argument("--layout", type=Path, default=None)
    ap.add_argument("--force", action="store_true")
    ns = ap.parse_args()
    repo = ns.repo.resolve()
    layout = ns.layout or repo / "docs" / "consolidation-3-layout.json"
    spec = json.loads(layout.read_text(encoding="utf-8"))

    pkg = repo / "fov3d"
    pkg.mkdir(exist_ok=True)
    compat = pkg / "_compat.py"
    compat_text = '''"""Internal helper for the sealed-engine compatibility facade."""\nfrom __future__ import annotations\n\nfrom importlib import import_module\n\n\ndef reexport_legacy(namespace: dict, legacy_name: str) -> None:\n    module = import_module(legacy_name)\n    public = getattr(module, "__all__", None)\n    if public is None:\n        public = [name for name in dir(module) if not name.startswith("_")]\n    namespace["__legacy_module__"] = legacy_name\n    namespace["_legacy_impl"] = module\n    namespace["__all__"] = list(public)\n    for name in public:\n        namespace[name] = getattr(module, name)\n'''
    if compat.exists() and not ns.force and compat.read_text(encoding="utf-8") != compat_text:
        raise SystemExit(f"refusing to overwrite {compat}; pass --force only after review")
    compat.write_text(compat_text, encoding="utf-8")

    top_init = pkg / "__init__.py"
    if not top_init.exists():
        top_init.write_text('"""Foveal Stereo Vision core API."""\n', encoding="utf-8")

    created = []
    for row in spec["mappings"]:
        legacy = row["legacy"]
        new = row["new"]
        path = module_path(repo, new)
        ensure_packages(repo, new)
        text = wrapper_text(legacy, bool(row.get("cli")))
        if path.exists() and not ns.force and path.read_text(encoding="utf-8") != text:
            raise SystemExit(f"refusing to overwrite {path}; pass --force only after review")
        path.write_text(text, encoding="utf-8")
        created.append(str(path.relative_to(repo)))

    print(f"[consolidation3-facade-build] created={len(created)}")
    for p in created:
        print(p)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
