"""Foveal Stereo Vision core API.

``fov3d`` is the stable conceptual API; ``tools/*`` is the sealed compatibility engine
behind it (docs/fov3d-api.md).  Every ``fov3d`` module re-exports one sealed module
unchanged (generated by tools/dev/build_fov3d_facade.py from
docs/consolidation-3-layout.json).

Package plumbing, the same the sealed entry points already do: the sealed modules import
their siblings by bare name (``from fsg_geometry import ...``) and rely on their
directory being on ``sys.path`` -- every sealed entry point runs
``sys.path.insert(0, <tools>)`` first.  Importing ``fov3d`` does the same, so a facade
module can be imported on its own.  It also refuses to run if ``tools`` would resolve to
anything other than this repository's ``tools/``.

Two interpreters, as for the sealed engine: ``fov3d.rendering.blender`` and
``fov3d.rendering.foveated`` import ``bpy`` and load only inside Blender; the others load
in the host ``.venv``.  ``fov3d.stereo.core`` and the Classroom ``matcher``, ``epistemic``
and ``run`` modules need OpenCV, which Blender's Python lacks, so they load only on the host.
"""
from __future__ import annotations

import importlib.util as _ilu
from pathlib import Path as _Path
import sys as _sys

_REPO = _Path(__file__).resolve().parent.parent
_TOOLS = _REPO / "tools"

if str(_TOOLS) not in _sys.path:
    _sys.path.insert(0, str(_TOOLS))

_spec = _ilu.find_spec("tools")
if _spec is None or _TOOLS not in [_Path(p).resolve() for p in (_spec.submodule_search_locations or [])]:
    raise ImportError(
        f"fov3d requires the sealed engine at {_TOOLS}; 'tools' resolves to "
        f"{None if _spec is None else list(_spec.submodule_search_locations or [_spec.origin])}. "
        f"Run from the repository root or put {_REPO} on PYTHONPATH."
    )

ENGINE_DIR = _TOOLS
