"""Compatibility facade for :mod:`tools.multiobject2c_policy`.

Generated by Consolidation 3.  Scientific implementation remains sealed in the
minimal legacy engine; new code imports this conceptual namespace instead.
"""
from fov3d._compat import reexport_legacy

reexport_legacy(globals(), 'tools.multiobject2c_policy')
